### ISSUE TITLE
Logging Revamp

### ISSUE THREAD

**Issue by srwopschall** [LLNL/Tribol#14]
- Update all logging to use SLIC, and use SLIC_<>_ROOT where appropriate so only rank = 0 outputs info, warnings, and errors.
- Add verbosity options? Suppress warnings?

**Comment by ebchin** [comment]
We also need to update/deprecate the `TRIBOL_DEBUG` and `TRIBOL_DEBUG_LOG` sections in https://github.com/LLNL/Tribol/blob/develop/src/tribol/common/types.hpp.in (see #20).
