### ISSUE TITLE
Tribol Build issues

### ISSUE THREAD

**Issue by thartland** [LLNL/Tribol#6]
I tried to build Tribol on my personal machine (Ubuntu 20.04) using the directions from the README file

`python3 scripts/uberenv/uberenv.py --project-json=scripts/spack/devtools.json --spack-config-dir=scripts/spack/configs/linux_ubuntu_20 --prefix=../tribol_devtools`

The error is related to the spack activation of py-shinx

`tribol_devtools/spack/bin/spack activate -f py-sphinx`

```
==> Warning: spack activate is deprecated in favor of environments and will be removed in v0.19.0
==> Error: py-sphinx is not an extension.
```

I see py-sphinx listed in `tribol_devtools/spack/bin/spack list`. This issue might be related to my inexperience with spack but any input would be appreciated.

Also, are there plans to include a `toss_4` spack config in order to build Tribol on TOSS 4 systems?

**Comment by ebchin** [comment]
Hi @thartland ,

The devtools build hasn't been tested in a while and will need to be updated in a future release.  Go ahead and skip to the [Installing Dependencies](https://github.com/LLNL/Tribol#installing-dependencies) part of the readme and see if you are able to build.  The devtools generally aren't needed for usage of Tribol, so you should be OK skipping their setup.
